---
- name: Instalar Kubernetes en EC2
  hosts: k8s
  become: true

  vars:
    pod_network_cidr: "10.244.0.0/16"

  tasks:
    - name: Actualizar sistema
      ansible.builtin.command: dnf -y upgrade
      changed_when: false

    - name: Instalar dependencias
      ansible.builtin.dnf:
        name:
          - curl
          - wget
          - vim
          - git
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Añadir repo Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'

    - name: Instalar containerd
      ansible.builtin.dnf:
        name: containerd.io
        state: present

    - name: Configurar containerd
      ansible.builtin.shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
        systemctl enable containerd
        systemctl restart containerd
      args:
        creates: /etc/containerd/config.toml
        warn: false

    - name: Desactivar swap
      ansible.builtin.shell: |
        swapoff -a
        sed -i '/ swap / s/^/#/' /etc/fstab
      changed_when: false

    - name: Configurar parámetros del kernel
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        mode: '0644'

    - name: Aplicar sysctl
      ansible.builtin.command: sysctl --system
      changed_when: false

    - name: Cargar módulo br_netfilter
      ansible.builtin.command: modprobe br_netfilter
      changed_when: false

    - name: Añadir repo Kubernetes
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
                 https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        mode: '0644'

    - name: Instalar kubelet, kubeadm, kubectl
      ansible.builtin.dnf:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Habilitar kubelet
      ansible.builtin.systemd:
        name: kubelet
        enabled: true

    - name: Inicializar el clúster
      ansible.builtin.command: kubeadm init --pod-network-cidr={{ pod_network_cidr }}
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Configurar kubectl para ec2-user
      become: true
      become_user: ec2-user
      ansible.builtin.shell: |
        mkdir -p ~/.kube
        cp /etc/kubernetes/admin.conf ~/.kube/config
        chown ec2-user:ec2-user ~/.kube/config
      changed_when: false

    - name: Tolerar pods en master
      become: true
      become_user: ec2-user
      ansible.builtin.command: kubectl taint nodes --all node-role.kubernetes.io/control-plane- || true
      changed_when: false

    - name: Instalar flannel
      become: true
      become_user: ec2-user
      ansible.builtin.command: >
        kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      changed_when: false

    - name: Instalar Ingress Controller
      become: true
      become_user: ec2-user
      ansible.builtin.command: >
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/baremetal/deploy.yaml
      changed_when: false
...
